export const IMG = {
  "new": "https://rygg-gaard.no/fpl/img/new.png",
  "new2": "https://rygg-gaard.no/fpl/img/new2.png"
}

export const FIXTURES = {
    "ARS" : [
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 4 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
    ],
    "AVL" : [
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
    ],
    "BOU" : [
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
    ],
    "BRE" : [
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
    ],
    "BHA" : [
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
    ],
    "BUR" : [
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
    ],
    "CHE" : [
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
    ],
    "CRY" : [
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 4 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
    ],
    "EVE" : [
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
    ],
    "FUL" : [
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
    ],
    "LIV" : [
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
    ],
    "LUT" : [
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 5 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
    ],
    "MCI" : [
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
    ],
    "MUN" : [
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
    ],
    "NEW" : [
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
    ],
    "NFO" : [
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
    ],
    "SHU" : [
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
    ],
    "TOT" : [
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
    ],
    "WHU" : [
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "WOL", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "WOL", "site" : "A", "fdr" : 2 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
    ],
    "WOL" : [
      { "opponent" : "MUN", "site" : "A", "fdr" : 3 },
      { "opponent" : "BHA", "site" : "H", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "A", "fdr" : 2 },
      { "opponent" : "CRY", "site" : "A", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "H", "fdr" : 4 },
      { "opponent" : "LUT", "site" : "A", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "H", "fdr" : 5 },
      { "opponent" : "AVL", "site" : "H", "fdr" : 3 },
      { "opponent" : "BOU", "site" : "A", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "H", "fdr" : 4 },
      { "opponent" : "SHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "TOT", "site" : "H", "fdr" : 3 },
      { "opponent" : "FUL", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "A", "fdr" : 4 },
      { "opponent" : "BUR", "site" : "H", "fdr" : 2 },
      { "opponent" : "NFO", "site" : "H", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "A", "fdr" : 2 },
      { "opponent" : "CHE", "site" : "H", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "A", "fdr" : 3 },
      { "opponent" : "EVE", "site" : "H", "fdr" : 2 },
      { "opponent" : "BHA", "site" : "A", "fdr" : 3 },
      { "opponent" : "MUN", "site" : "H", "fdr" : 4 },
      { "opponent" : "CHE", "site" : "A", "fdr" : 3 },
      { "opponent" : "BRE", "site" : "H", "fdr" : 3 },
      { "opponent" : "TOT", "site" : "A", "fdr" : 3 },
      { "opponent" : "SHU", "site" : "H", "fdr" : 2 },
      { "opponent" : "NEW", "site" : "A", "fdr" : 4 },
      { "opponent" : "FUL", "site" : "H", "fdr" : 2 },
      { "opponent" : "BOU", "site" : "H", "fdr" : 2 },
      { "opponent" : "AVL", "site" : "A", "fdr" : 3 },
      { "opponent" : "BUR", "site" : "A", "fdr" : 2 },
      { "opponent" : "WHU", "site" : "H", "fdr" : 3 },
      { "opponent" : "NFO", "site" : "A", "fdr" : 2 },
      { "opponent" : "ARS", "site" : "H", "fdr" : 4 },
      { "opponent" : "LUT", "site" : "H", "fdr" : 2 },
      { "opponent" : "MCI", "site" : "A", "fdr" : 5 },
      { "opponent" : "CRY", "site" : "H", "fdr" : 2 },
      { "opponent" : "LIV", "site" : "A", "fdr" : 4 },
    ],
  }
export const TEAMS = Object.keys(FIXTURES);
export const POSITIONS = ["GK", "DEF", "MID", "FWD"];

export class PlayerData {
  constructor(team, pos, id, play){
    this.team = team;
    this.playing = play;
    this.pos = pos;
    this.id = id;
    this.fdr = 6;
  }
  get_fixture(gw){
    return FIXTURES[this.team][gw-1];
  }
}

export function renderFixtures() {
  var team_rows = []
  for (const [i, team] of TEAMS.entries()) {
    var fix_cols = []
    for (const [j, f] of FIXTURES[team].entries()) {
      fix_cols.push(
        <div className='col f1 brd mid' key={j}>
          {f.opponent}<br />{f.site}
        </div>
      )
    }
    team_rows.push(
      <div className='row f1' key={i}>
        <div className='col f1 brd'>
          {team}
        </div>
        {fix_cols}
      </div>
    )
  }

  return (
    <div className="col">
      {team_rows}
    </div>
  );
}

